data:
  source: drive

  dataset_roots:
    local: .
    drive: /content/drive/MyDrive/mkn_data_merged/sft_merged_sample

  image_roots:
    local: .
    drive: /content/drive/MyDrive/mkn2_img

  splits:
    train: train_sft.jsonl
    validation: val_sft.jsonl
    test: eval_sft.jsonl

  use_test_split: true

  cache_images: true
  cache_size: 128

  dataset_name: lfixfey/mkn_vlm_dataset

  hf_splits:
    train: data/sft_dataset/train.jsonl
    validation: data/sft_dataset/val.jsonl
    test: data/sft_dataset/test.jsonl
