data:
  source: local

  splits:
    train: data/sft/train.jsonl
    validation: data/sft/val.jsonl
    test: data/sft/test.jsonl

  image_roots:
    local: .
    drive: /content/drive/MyDrive/rutilahu-vlm/data/mkn_img

  use_test_split: true

  cache_images: true
  cache_size: 128

  dataset_name: lfixfey/mkn_vlm_dataset

  hf_splits:
    train: data/sft/train.jsonl
    validation: data/sft/val.jsonl
    test: data/sft/test.jsonl
